### PR TITLE
Cause second fork, write out PID file

### PR DESCRIPTION
**Pull request by paulehoffman**
This allows an external program to kill the daemon by knowing the PID filename, which is fixed. In order for this to work, you need to do a second fork, as described in "Python Cookbook" section 12.14.

### CODE REVIEW

**Comment by shuque** [comment]
Thanks Paul. A few comments ..

The PID file is a good feature, and was on my todo list. The 2nd fork() is not actually needed for that, but recommended for other reasons (losing session group leadership and isolating the daemon from controlling tty acquisition). Not strictly necessary though - even W. Richard Steven's APUE book examples don't do the 2nd fork.

Your fixed pathname for the pidfile doesn't allow you to run multiple versions of the server on the same system (e.g. by binding each to a separate port and/or address). Also, some people don't like putting the pidfile in the shared /tmp directory for security reasons on multi-user systems.

I'll merge this PR in, but you might see a follow-on commit from me to address the latter issue (with a working directory and pidfile options in the config file - the default without those settings could go to /tmp).

**Comment by paulehoffman** [comment]
Yeah, I definitely cut corners with the fixed file name, and I thought of the reason you gave. But I think the second fork may be needed; I tried with one existing fork, and the file created always said the PID was 0.

Looking forward to future commits with varying-named PID file; the trick will be how the outside process will be able to discover that file name.

**Comment by shuque** [comment]
I did a quick test from a commit before the double fork, added the pidfile construction, and it worked fine. I suspect you had a bug somewhere in your code. But the double fork is in now, so it may not be worth investigating that.

For the varying pidfile, the external program could look in the config file to see what it is, e.g. by examining the "pidfile" or "workdir" parameters.

**Comment by paulehoffman** [comment]
I like the idea of a "pidflie" option to the config, with writing to the fixed file name in /tmp if it is not specified.

**Pull request merged**
